name: yuk_kuy_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  art_sweetalert: ^0.0.5
  cupertino_icons: ^1.0.5
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_staggered_grid_view: ^0.6.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  lottie_player: ^0.0.5
  pull_to_refresh: ^2.0.0
  sign_button: ^2.0.3
  social_media_flutter: ^0.0.2
  tuple: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: center
  image_dark: assets/images/splash.png
  color_dark: "#ffffff"
  android_12:
    android_gravity: center
    image: assets/images/splash.png
    color: "#ffffff"
    image_dark: assets/images/splash.png
    color_dark: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    # - assets/models/
